routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/pointages', 'PointageController@index')->name('pointages');
Route::get('/users', 'PointageController@listComptable')->name('users');
Route::get('/pointage', 'PointageController@create')->name('pointage');
Route::get('/pointagehoraire', 'PointageController@createMatricule')->name('pointagehoraire');
Route::post('/pointagehoraire', 'PointageController@store');
Route::post('/pointage/{id}', 'PointageController@testPointage');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::post('pointages/{id}/update', 'PointageController@update');
Route::resource('pointages', 'PointageController');
Route::get('404', ['as' => '404', 'uses' => 'ErrorController@notfound']);

app/Pointage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pointage extends Model
{
    /**
     * @var string
     */
    protected $table = "pointages";

    /**
     * @var string
     */
    protected $primaryKey = 'id';

    protected $heure_pointage = ['heure_pointage'];

    protected $fillable = ['matricule', 'code', 'user_id', 'heure_pointage'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    public function isRole()
    {
        return $this->user_type;
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/helpers.php
<?php
/**
 * Created by PhpStorm.
 * User: agne
 * Date: 11/16/18
 * Time: 3:01 PM
 */

if (!function_exists('currentRoute')){
    function currentRoute(...$routes){
        foreach ($routes as $route){
            if (request()->url() == $route){
                return ' active';
            }
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ErrorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ErrorController extends Controller
{
    public function notFound()
    {
        return view('errors.404');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PointageController.php
<?php

namespace App\Http\Controllers;

use App\Pointage;
use App\User;
use Carbon\Carbon;
use Illuminate\Auth\Access\Gate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class PointageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /*if (!Gate::allows('isAdmin')){
            abort(404, "Desole, cette page est innaccéssible");
        }*/
        $pointages = DB::table('pointages')
            ->join('users','users.id', '=', 'pointages.user_id')
            ->select('users.name')
            ->addSelect('pointages.*')
            ->get();
       // dump($pointages);die();
       return view('admin.pointage.index', ['pointages' => $pointages]);
    }

    public function listComptable()
    {
        $listComptables = User::where('user_type','comptable')->get();
        return view('admin.pointage.users', ['listsComptables' => $listComptables]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $current_user = auth()->user()->id;
        $code = substr(base_convert(sha1(uniqid(mt_rand())), 16, 36), 0, 5);
        return view('comptable.pointage', ['code' => $code, 'current_user' =>$current_user]);
    }

    public function createMatricule()
    {
        $code = substr(base_convert(sha1(uniqid(mt_rand())), 16, 36), 0, 5);
        return view ('admin.pointage.pointage',['code' => $code]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $hash = Hash::make($request->get('password'));
        $user = auth()->user();

        $pointage = new Pointage();
        $pointage->matricule = $request->get('matricule');
        $pointage->user_id = $user->id;
        $pointage->heure_pointage = Carbon::now()->addMinute(-15)->endOfMinute();

        $pointage->password = $hash;
        $pointage->code = $request->get('code');
        $pointage->save();
        return response()->json(['success', 'Data is successfuly added']);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function testPointage(Request $request , $id)
    {
        $pointage =Pointage::find($id);
        $matricule = $pointage->matricule = $request->get('matricule');
        $current_user = auth()->user();

        $qb = DB::table('pointages')
            ->where('pointages.matricule','=', $matricule)
            ->first();

        $user_id = $qb->user_id;
        //dump($user_id);die();
        $user_matricule = $qb->matricule;

        if($current_user->id != $user_id && $matricule != $user_matricule ){
            Session::flash('message','Matricule non valide' );
            return Redirect::to('/pointage');

        }else{
            $pointage->user_id = $user_id;
            $pointage->password = $qb->password ;
            $pointage->heure_pointage = Carbon::now()->addMinute(-15)->endOfMinute();
            $pointage->code = $request->get('code');
            $pointage->save();
        }

        return response()->json(['success', 'Data is successfuly added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pointage = Pointage::find($id);
        $user = DB::table('pointages')
            ->join('users','users.id','=', 'pointages.user_id')
            ->where('pointages.id','=',$id)
            ->first();
        //dump($user);die();
        $code = substr(base_convert(sha1(uniqid(mt_rand())), 16, 36), 0, 5);
        return view('admin.pointage.edit', ['pointage'=> $pointage, 'code'=>$code, 'user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pointage = Pointage::find($id);
        $pointage->matricule = $request->get('matricule');
        $pointage->heure_pointage = Carbon::now()->addMinute(-15)->endOfMinute();
        $pointage->code = $request->get('code');
        $pointage->save();
        return response()->json(['success', 'Data is successfuly added']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <style>
        .navbar{
            margin-bottom: 2rem;
        }
    </style>
</head>

<body>
@can('isAdmin')
<nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-inverse bg-primary navbar-laravel">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{ url('/pointages') }}">Tableau de bord</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{ currentRoute(route('pointages.index')) }}">
                    <a class="nav-link" href="{{url('/pointages')}}">Liste des Pointages</a>
                </li>
                <li class="nav-item {{ currentRoute(route('users')) }}">
                    <a class="nav-link"href="{{url('/users')}}">Liste des Comptables</a>
                </li>
            </ul>
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item">
                        @if (Route::has('register'))
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        @endif
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>

        </div>
    </div>
</nav>

<div class="container">
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    @yield('content')
</div><!-- /.container -->
    @elsecan('isComptable')
    <div class="alert-danger mt-5" style="text-align: center">
        <h2>Cette pages est indisponible <br> pour vous</h2>
    </div>
@endcan
</body>
</html>

resources/views/admin/pointage/edit.blade.php
@extends('admin.layout')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-4 offset-lg-4">
                    <div class="card-header bg-primary">
                        <p><h4 style="text-align: center; color: white;"> {{$user->name}}</h4></p>
                    </div>
                    <div class="card-body">

                    </div>
                </div>
                <br>
                <form method="post" action="{{url('/pointage')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="alert alert-success" id="success" style="display: none;">Modification du pointage effectuer avec succees</div>
                    <input type="hidden" value="{{$pointage->id}}" id="pointage_id">
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="matricule">Numero Matricule:</label>
                            <input type="text" class="form-control" name="matricule" id="matricule" value="{{$pointage->matricule}}">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="code">Reneigner le code suivant : <strong id="label_code">{{$code}}</strong></label>
                            <input type="text" id="input_code" class="form-control" name="code">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4" style="margin-top:60px">
                            <button id="pointageSubmit" type="submit" class="btn btn-success">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script>
            jQuery(function () {
                jQuery('#pointageSubmit').click(function (e) {
                    e.preventDefault();
                    var code = jQuery('strong#label_code').html();
                    var code_input = jQuery('#input_code').val();
                    var pointage_id = jQuery('#pointage_id').val();
                    console.log(code_input);
                    if (code == code_input) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });
                        jQuery.ajax({
                            url: "http://127.0.0.1:8000/pointages/"+ pointage_id +"/update",
                            method: 'post',
                            data: {
                                matricule : jQuery('#matricule').val(),
                                code : jQuery('#input_code').val(),
                            } ,
                            success: function (result) {
                                jQuery('div#success').css('display','block');
                                jQuery('#matricule').val("");
                                jQuery('#password').val("");
                                jQuery('#input_code').val("");
                                jQuery('button#pointageSubmit').css('cursor','none');
                                var code = jQuery('strong#label_code').html("")
                            }
                        });
                    } else
                    {
                        jQuery('#input_code').css('border-color', 'red');
                        jQuery('#input_code').val("Le code est : {{$code}}");
                    }
                });
            });
        </script>
    </div>
@endsection

resources/views/admin/pointage/form.blade.php
{!! Form::model($pointages, [
    'route' => $pointages->id ? ['compatble.update', $pointages] : 'comptable.pointage',
    'method' => $pointages->id ? 'PUT' : 'POST'
]) !!}

<div class="row">
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('matricule')) has-danger @endif">
            {!! Form::label('matricule', 'Matricule') !!}
            {!! Form::text('matricule', null, ['class' => 'form-control']) !!}
            @if($errors->first('matricule'))
                <small class="form-control-feedback">{{ $errors->first('matricule') }}</small>
            @endif
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('slug')) has-danger @endif">
            {!! Form::label('password', 'Password') !!}
            {!! Form::password('password', null, ['class' => 'form-control']) !!}
            @if($errors->first('password'))
                <small class="form-control-feedback">{{ $errors->first('password') }}</small>
            @endif
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('matricule')) has-danger @endif">
            {!! Form::label('code', 'code') !!}
            {!! Form::text('CODE', null, ['class' => 'form-control']) !!}
            @if($errors->first('code'))
                <small class="form-control-feedback">{{ $errors->first('code') }}</small>
            @endif
        </div>
    </div>
</div>
{!! Form::submit($pointages->id ? 'Update' : 'Pointage', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}

resources/views/admin/pointage/index.blade.php
@extends('admin.layout')

@section('content')
<h1>Gestion des heures de pointages</h1>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Users</th>
        <th>Numero matricule</th>
        <th>Heure de Pointage</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach($pointages as $pointage)
    <tr>
        <td>{{ $pointage->name }}</td>
        <td>{{ $pointage->matricule }}</td>
        {{--<td>{{ $pointage->heure_pointage->format('d/m/Y H:i') }}</td>--}}
        <td>{{ date('H:i', strtotime($pointage->heure_pointage)) }}</td>
        <td>
            <a href="{{action('PointageController@edit', $pointage->id)}}" class="btn btn-primary">Modifier</a>
        </td>
    </tr>
    @endforeach
    </tbody>
</table>


@endsection

resources/views/admin/pointage/pointage.blade.php
@extends('../layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <form method="post" action="{{url('/pointagehoraire')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="alert alert-success" id="success" style="display: none;">Pointage effectuer</div>
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="matricule">Numero Matricule:</label>
                            <input type="text" class="form-control" name="matricule" id="matricule" placeholder="GDK004887">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="password">Mot de passe</label>
                            <input type="password" id="password" class="form-control" name="password">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="code">Reneigner le code suivant : <strong id="label_code">{{$code}}</strong></label>
                            <input type="text" id="input_code" class="form-control" name="code" placeholder="code">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4" style="margin-top:60px">
                            <button id="pointageSubmit" type="submit" class="btn btn-success">Pointer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script>
            jQuery(function () {
                jQuery('#matricule').val("");
                jQuery('#password').val("");
                jQuery('#input_code').val("");
                jQuery('#pointageSubmit').click(function (e) {
                   e.preventDefault();
                    var code = jQuery('strong#label_code').html();
                    var code_input = jQuery('#input_code').val();
                    //console.log(code_input);
                   if (code == code_input) {
                       $.ajaxSetup({
                           headers: {
                               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                           }
                       });
                       jQuery.ajax({
                           url: "{{url('/pointagehoraire')}}",
                           method: 'post',
                           data: {
                               matricule : jQuery('#matricule').val(),
                               password : jQuery('#password').val(),
                               code : jQuery('#input_code').val(),
                           } ,
                           success: function (result) {
                               //console.log(result);
                               jQuery('div#success').css('display','block');
                               jQuery('#matricule').val("");
                               jQuery('#password').val("");
                               jQuery('#input_code').val("");
                               jQuery('button#pointageSubmit').css('cursor','none');
                           }
                       });
                   } else
                   {
                       jQuery('#input_code').css('border-color', 'red');
                       jQuery('#input_code').val("Le code est : {{$code}}");
                   }
                });
            });
        </script>
        </div>
@endsection

resources/views/admin/pointage/users.blade.php
@extends('admin.layout')

@section('content')
<h1>Liste des comptables</h1>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Users</th>
        <th>Email</th>
        <th>Fonction</th>
    </tr>
    </thead>
    <tbody>
    @foreach($listsComptables as $listsComptable)
    <tr>
        <td>{{ $listsComptable->name }}</td>
        <td>{{ $listsComptable->email }}</td>
        <td>{{ $listsComptable->user_type }}</td>
    </tr>
    @endforeach
    </tbody>
</table>


@endsection

resources/views/comptable/form.blade.php
{!! Form::model($pointages, [
    'route' => $pointages->id ? ['compatble.update', $pointages] : 'comptable.pointage',
    'method' => $pointages->id ? 'PUT' : 'POST'
]) !!}

<div class="row">
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('matricule')) has-danger @endif">
            {!! Form::label('matricule', 'Matricule') !!}
            {!! Form::text('matricule', null, ['class' => 'form-control']) !!}
            @if($errors->first('matricule'))
                <small class="form-control-feedback">{{ $errors->first('matricule') }}</small>
            @endif
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('slug')) has-danger @endif">
            {!! Form::label('password', 'Password') !!}
            {!! Form::password('password', null, ['class' => 'form-control']) !!}
            @if($errors->first('password'))
                <small class="form-control-feedback">{{ $errors->first('password') }}</small>
            @endif
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group @if($errors->first('matricule')) has-danger @endif">
            {!! Form::label('code', 'code') !!}
            {!! Form::text('CODE', null, ['class' => 'form-control']) !!}
            @if($errors->first('code'))
                <small class="form-control-feedback">{{ $errors->first('code') }}</small>
            @endif
        </div>
    </div>
</div>
{!! Form::submit($pointages->id ? 'Update' : 'Pointage', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}

resources/views/comptable/pointage.blade.php
@extends('../layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @if (Session::has('message'))
                    <div class="alert alert-error">{{ Session::get('message') }}</div>
                @endif
                <form method="post" action="{{url('/pointage')}}" enctype="multipart/form-data">
                    @csrf
                    <div class="alert alert-success" id="success" style="display: none;">Pointage effectuer avec succées</div>
                    <div class="row">
                        <input type="hidden" id="user_id" value="{{$current_user}}">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="matricule">Numero Matricule:</label>
                            <input type="text" class="form-control" name="matricule" id="matricule" placeholder="GDK004887" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="password">Mot de passe</label>
                            <input type="password" id="password" class="form-control" name="password" required>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4">
                            <label for="code">Reneigner le code suivant : <strong id="label_code">{{$code}}</strong></label>
                            <input type="text" id="input_code" class="form-control" name="code" placeholder="code" required>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="form-group col-md-4" style="margin-top:60px">
                            <button id="pointageSubmit" type="submit" class="btn btn-success">Pointer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script>
            jQuery(function () {
                jQuery('#matricule').val("");
                jQuery('#password').val("");
                jQuery('#input_code').val("");
                jQuery('#pointageSubmit').click(function (e) {
                    e.preventDefault();
                    var code = jQuery('strong#label_code').html();
                    var code_input = jQuery('#input_code').val();
                    var user_id = jQuery('#user_id').val();
                   // var matricule = jQuery('#matricule').val();
                    //console.log(code_input);
                   /* if (code_input == ""){
                        jQuery('#input_code').css('border-color', 'red');
                        jQuery('#input_code').val("Le champ est vide ");
                    }
                    if (matricule == ""){
                        jQuery('#matricule').css('border-color', 'red');
                        jQuery('#matricule').val("Le champ est vide ");
                    } */
                    if (code == code_input) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });
                        jQuery.ajax({
                            url: "http://127.0.0.1:8000/pointage/"+ user_id ,
                            method: 'post',
                            data: {
                                matricule : jQuery('#matricule').val(),
                                password : jQuery('#password').val(),
                                code : jQuery('#input_code').val(),
                            } ,
                            success: function (result) {
                                //console.log(result);
                                jQuery('div#success').css('display','block');
                                jQuery('#matricule').val("");
                                jQuery('#password').val("");
                                jQuery('#input_code').val("");
                                jQuery('button#pointageSubmit').css('cursor','none');
                            },
                            error: function (result) {
                                jQuery('#matricule').val("");
                                jQuery('#matricule').css('border-color', 'red');
                                jQuery('#matricule').attr('placeholder', 'Matricule Incorrect');
                            }
                        });
                    } else
                    {
                        jQuery('#input_code').css('border-color', 'red');
                    }
                });
            });
        </script>
    </div>
@endsection